// ^TypeScript.
// ^TypeScript es un lenga¿uaje de programación de codigo abierto realizado por Microsoft para extender JavaScript, el cual TypeScript es un lenguaje de programación tipado estaticamente, por lo cual nos va a permitir ponerle tipos de datos a las variables, funciones y otros elementos del codigo. Esta creado justamente para hacer aplicaciones JavaScript de manera robusta y solida aunque sean escalables (grandes y complejas). Cabe mencionar que al ser TypeScript basado en JavaScript si se sabe este ultimo, se tiene un conocimiento aproximado de un 80% de TypeScript, ya que la sintaxis y la mayoria de caracterisiticas de TypeScript son iguales a las de JavaScript.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// ~Observadores
// ~En TypeScript existe una funcion cursiosa, la cual consiste en que si queremos por ejemplo vincular un HTML a dicho lenguaje este no lo reconocera ya que los scripts de HTML leen unicamente JavaScript, ahora bien esto significa que cada vez que nosotros tenemos un archivo de TypeScript tenemos que compilarlo en .js para que este funcione, ya que los archivos web funcionan con HTML y JS, por lo cual nosotros podemos copilarlo manualmente usando "tsc nombreArchivo.ts". O otra manera de hacerlo es utilizar una caracteristica propia de TypeScript la cual es el uso de los observadores. El cual dicha caracteristica va a estar observando los cambios y a partir del momento que se cambie va a generar automaticamente la copilacion en JS cuando guardemos. De igual manera se cuenta con un inicializador para activar observadores de manera que todos nuestros archivos TS de nuestro proyecto sean observados.
console.log('=========== Observadores. ==========='); // *Indica el inicio de la sección de observadores.

// &Activar modo observador en archivos TS.
// &Para poder copilar de manera automatica nuestros archivos de TS, debemos activar un observador, el cual padar poder realizar dicha accion deberemos escribir de manera manual en nuestra consola el comando de tsc junto con el nombre de nuestro archivo y su estencion .ts, ademas de usar el comando -w el cual al ejecutarlo iniciara el modo observador en dicho archivos de TypeScript. El cual al ejecutar dicho comando se mostrara mensajes hacerca de que esta iniciando la compilacion en modo observador. El cual a partir de cada momento que guardemos nuestro archivo de TS lo transformara a un archivo JS.
console.log('Activar observador: tsc nombreArchivo.ts -w');

// &Activar modo observador en proyectos.
// &Si bien podemos activar un observador individual para cada uno de nuestros elementos TS, existe un proplema el cual es que si tenemos muchos archivos TS en nuestro proyecto no podemos ejecutar tantos observadores ya que esto consumiria mucho de nuestro dispositivo, por lo cual existe un observador o inicializador de observadores para todos los TS de un proyecto, el cual adicionalmente esto realizara la accion de activar observadores en todo el proyecto, vamos a tener adcionalmnente ciertas configuraciones para ayudarnos con los errores, para ser mas estrictos, para que algunos tipos de errores no los detecte, entre mucho mas. Para ello unicament etenemos que usar el comando de TS de tsc ademas del comando -init. Por lo que de esa forma vamos a iniciar en nuestro proyecto los observadores. El cual al ejecutar dicho comando creara un archivo tsconfig.json, el cual contiene lo antes mencionado
