"use strict";
// ^TypeScript.
// ^TypeScript es un lenguaje de programación de **código abierto** desarrollado por **Microsoft**, cuyo objetivo principal es **extender JavaScript** añadiendo un **sistema de tipos estático**. Esto significa que TypeScript permite definir tipos de datos para variables, funciones, parámetros, objetos y otros elementos del código, lo cual ayuda a detectar errores **en tiempo de desarrollo** y no únicamente en tiempo de ejecución. Gracias a este enfoque, TypeScript facilita la creación de aplicaciones JavaScript **más robustas, seguras, mantenibles y escalables**, especialmente en proyectos grandes y complejos. Es importante destacar que TypeScript está completamente basado en JavaScript, por lo que si ya se domina JavaScript, se puede decir que aproximadamente un **80% del conocimiento es transferible**, ya que la sintaxis y la mayoría de las características son compartidas, añadiendo TypeScript principalmente capas de tipado y herramientas adicionales de desarrollo.
Object.defineProperty(exports, "__esModule", { value: true });
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ~Observadores.
// ~En TypeScript existe una característica muy importante relacionada con el proceso de compilación. A diferencia de JavaScript, los navegadores y los archivos HTML **no pueden ejecutar directamente archivos `.ts`**, ya que solo entienden JavaScript. Por esta razón, **todo archivo TypeScript debe ser compilado a JavaScript** antes de poder ser utilizado en una aplicación web. Esta compilación puede realizarse de forma manual usando el compilador de TypeScript (`tsc`). Sin embargo, cuando se trabaja en proyectos reales, compilar manualmente cada cambio resulta ineficiente. Para resolver este problema, TypeScript ofrece el **modo observador (watch mode)**, el cual se encarga de **monitorear los cambios en los archivos `.ts`** y generar automáticamente la versión `.js` cada vez que se guarda el archivo. Además, TypeScript permite activar observadores a nivel de proyecto completo, facilitando el desarrollo continuo y reduciendo errores humanos.
console.log('=========== Observadores. ==========='); // *Indica el inicio de la sección dedicada al uso de observadores en TypeScript.
// &Activar modo observador en archivos TS.
// &Para poder compilar de forma automática un archivo específico de TypeScript, es necesario activar el modo observador utilizando el compilador `tsc`. Esto se hace ejecutando el comando `tsc` seguido del nombre del archivo y su extensión `.ts`, junto con el parámetro `-w` (watch). Al ejecutar este comando, TypeScript entra en un estado de observación constante, mostrando mensajes en consola que indican que el archivo está siendo monitoreado. A partir de ese momento, **cada vez que el archivo `.ts` se guarda**, el compilador generará automáticamente su correspondiente archivo `.js`, evitando la necesidad de compilar manualmente en cada cambio.
console.log('Activar observador: tsc nombreArchivo.ts -w'); // *Ejemplo del comando para activar el modo observador en un archivo individual.
// &Activar modo observador en proyectos.
// &Aunque es posible activar un observador por cada archivo TypeScript, esto no es una práctica eficiente cuando el proyecto contiene múltiples archivos `.ts`, ya que implicaría ejecutar varios procesos simultáneos, lo cual puede consumir recursos innecesarios del sistema. Para solucionar esto, TypeScript ofrece la posibilidad de **configurar un observador a nivel de proyecto**, permitiendo que todos los archivos `.ts` sean monitoreados automáticamente desde un solo comando. Además, esta configuración centralizada permite definir reglas adicionales como nivel de estrictitud, manejo de errores, rutas de salida, compatibilidad con versiones de JavaScript y más. Todo esto se gestiona mediante un archivo especial llamado `tsconfig.json`.
// ?Creación del archivo "tsconfig.json".
// ?Para crear el archivo de configuración del proyecto, se utiliza el comando `tsc` junto con la opción `-init`. Este comando genera automáticamente un archivo `tsconfig.json` en la raíz del proyecto. Dicho archivo contiene las configuraciones base del compilador de TypeScript, incluyendo opciones de compilación, reglas de tipado y parámetros que controlan el comportamiento general del proyecto. Este paso es fundamental para trabajar de forma profesional con TypeScript.
console.log('Crear archivo tsconfig.json: tsc -init'); // *Comando para inicializar la configuración del proyecto TypeScript.
// ?Activación de observadores en el proyecto.
// ?Una vez creado el archivo `tsconfig.json`, es posible activar el modo observador para **todo el proyecto** ejecutando únicamente el comando `tsc -w`. A partir de este momento, el compilador observará todos los archivos `.ts` definidos en la configuración y generará automáticamente sus versiones `.js` cada vez que se detecte un cambio. Como parte del proceso de compilación, TypeScript añade por defecto la instrucción `"use strict"` en los archivos JavaScript generados, lo cual activa el **modo estricto de JavaScript**, haciendo que el lenguaje sea más riguroso al validar errores, malas prácticas y usos inseguros del código.
console.log('Activación observadores proyecto: tsc -w'); // *Ejecuta el modo observador para todos los archivos TypeScript del proyecto.
